# Generated by Django 4.2.1 on 2023-05-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='avatar-chibi.png', null=True, upload_to='users/'),
        ),
    ]
